# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 538)
        MainWindow.setStyleSheet("background-color: rgb(0, 74, 112);")
        self.Login = QtWidgets.QWidget(MainWindow)
        self.Login.setObjectName("Login")
        self.frame = QtWidgets.QFrame(self.Login)
        self.frame.setGeometry(QtCore.QRect(100, 120, 391, 351))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 0.2);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt_user = QtWidgets.QLineEdit(self.frame)
        self.txt_user.setGeometry(QtCore.QRect(50, 100, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_user.setFont(font)
        self.txt_user.setStyleSheet("color: rgb(255, 255, 255)")
        self.txt_user.setText("")
        self.txt_user.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_user.setObjectName("txt_user")
        self.btn_login = QtWidgets.QPushButton(self.frame)
        self.btn_login.setGeometry(QtCore.QRect(90, 250, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setToolTipDuration(1)
        self.btn_login.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.txt_password = QtWidgets.QLineEdit(self.frame)
        self.txt_password.setGeometry(QtCore.QRect(50, 170, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_password.setFont(font)
        self.txt_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_password.setObjectName("txt_password")
        self.label = QtWidgets.QLabel(self.Login)
        self.label.setGeometry(QtCore.QRect(210, 20, 161, 121))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("_imgs/icon_title.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label.raise_()
        self.frame.raise_()
        #MainWindow.setCentralWidget(self.Login)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_user.setPlaceholderText(_translate("MainWindow", "User"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
