# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 596)
        MainWindow.setStyleSheet("background-color:rgb(0,0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_home = QtWidgets.QPushButton(self.frame)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0,80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout.addWidget(self.btn_home)
        self.btn_import = QtWidgets.QPushButton(self.frame)
        self.btn_import.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_import.setFont(font)
        self.btn_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_import.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0,80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        self.btn_tables = QtWidgets.QPushButton(self.frame)
        self.btn_tables.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tables.setFont(font)
        self.btn_tables.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_tables.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0,80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_tables.setObjectName("btn_tables")
        self.horizontalLayout.addWidget(self.btn_tables)
        self.btn_sobre = QtWidgets.QPushButton(self.frame)
        self.btn_sobre.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sobre.setFont(font)
        self.btn_sobre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sobre.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0,80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_sobre.setObjectName("btn_sobre")
        self.horizontalLayout.addWidget(self.btn_sobre)
        self.btn_contato = QtWidgets.QPushButton(self.frame)
        self.btn_contato.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_contato.setFont(font)
        self.btn_contato.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_contato.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 1px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0,80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_contato.setObjectName("btn_contato")
        self.horizontalLayout.addWidget(self.btn_contato)
        self.verticalLayout_11.addWidget(self.frame)
        self.Pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.Pages.setStyleSheet("background-color:rgb(0,80, 121)")
        self.Pages.setObjectName("Pages")
        self.pg_table = QtWidgets.QWidget()
        self.pg_table.setObjectName("pg_table")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pg_table)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tb_base = QtWidgets.QTabWidget(self.pg_table)
        self.tb_base.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tb_base.setFont(font)
        self.tb_base.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_base.setMouseTracking(False)
        self.tb_base.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tb_base.setAutoFillBackground(False)
        self.tb_base.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.tb_base.setTabPosition(QtWidgets.QTabWidget.North)
        self.tb_base.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tb_base.setElideMode(QtCore.Qt.ElideLeft)
        self.tb_base.setUsesScrollButtons(True)
        self.tb_base.setDocumentMode(False)
        self.tb_base.setTabsClosable(False)
        self.tb_base.setMovable(False)
        self.tb_base.setTabBarAutoHide(False)
        self.tb_base.setObjectName("tb_base")
        self.Base = QtWidgets.QWidget()
        self.Base.setObjectName("Base")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Base)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.Base)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tw_estoque = QtWidgets.QTreeWidget(self.Base)
        self.tw_estoque.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tw_estoque.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tw_estoque.setRootIsDecorated(False)
        self.tw_estoque.setHeaderHidden(False)
        self.tw_estoque.setObjectName("tw_estoque")
        self.verticalLayout_5.addWidget(self.tw_estoque)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.Base)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.tw_saida = QtWidgets.QTreeWidget(self.Base)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_saida.sizePolicy().hasHeightForWidth())
        self.tw_saida.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.tw_saida.setFont(font)
        self.tw_saida.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tw_saida.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tw_saida.setAcceptDrops(False)
        self.tw_saida.setToolTip("")
        self.tw_saida.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tw_saida.setAutoFillBackground(False)
        self.tw_saida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tw_saida.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tw_saida.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tw_saida.setAutoScroll(True)
        self.tw_saida.setAutoScrollMargin(17)
        self.tw_saida.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tw_saida.setRootIsDecorated(False)
        self.tw_saida.setUniformRowHeights(False)
        self.tw_saida.setItemsExpandable(True)
        self.tw_saida.setHeaderHidden(False)
        self.tw_saida.setExpandsOnDoubleClick(True)
        self.tw_saida.setObjectName("tw_saida")
        font = QtGui.QFont()
        font.setKerning(True)
        self.tw_saida.headerItem().setFont(0, font)
        self.tw_saida.header().setVisible(False)
        self.tw_saida.header().setCascadingSectionResizes(False)
        self.tw_saida.header().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.tw_saida)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.frame_2 = QtWidgets.QFrame(self.Base)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_gerar = QtWidgets.QPushButton(self.frame_2)
        self.btn_gerar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gerar.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 15px;\n"
"    background-color:rgb(0, 20, 30);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}\n"
"")
        self.btn_gerar.setObjectName("btn_gerar")
        self.verticalLayout_3.addWidget(self.btn_gerar)
        self.btn_estorno = QtWidgets.QPushButton(self.frame_2)
        self.btn_estorno.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btn_estorno.setFont(font)
        self.btn_estorno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_estorno.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 15px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}\n"
"")
        self.btn_estorno.setObjectName("btn_estorno")
        self.verticalLayout_3.addWidget(self.btn_estorno)
        spacerItem = QtWidgets.QSpacerItem(20, 9999999, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.tb_base.addTab(self.Base, "")
        self.Geral = QtWidgets.QWidget()
        self.Geral.setObjectName("Geral")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Geral)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.Geral)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_chart = QtWidgets.QPushButton(self.Geral)
        self.btn_chart.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_chart.setFont(font)
        self.btn_chart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_chart.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_chart.setObjectName("btn_chart")
        self.horizontalLayout_12.addWidget(self.btn_chart)
        self.btn_excel = QtWidgets.QPushButton(self.Geral)
        self.btn_excel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_excel.setFont(font)
        self.btn_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excel.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_excel.setObjectName("btn_excel")
        self.horizontalLayout_12.addWidget(self.btn_excel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.txt_filtro = QtWidgets.QLineEdit(self.Geral)
        self.txt_filtro.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_filtro.setFont(font)
        self.txt_filtro.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txt_filtro.setStyleSheet("color:rgb(255, 255, 255);")
        self.txt_filtro.setText("")
        self.txt_filtro.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_filtro.setObjectName("txt_filtro")
        self.verticalLayout_10.addWidget(self.txt_filtro)
        self.tw_geral = QtWidgets.QTableView(self.Geral)
        self.tw_geral.setObjectName("tw_geral")
        self.verticalLayout_10.addWidget(self.tw_geral)
        self.tb_base.addTab(self.Geral, "")
        self.verticalLayout_8.addWidget(self.tb_base)
        self.Pages.addWidget(self.pg_table)
        self.pg_home = QtWidgets.QWidget()
        self.pg_home.setObjectName("pg_home")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pg_home)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.pg_home)
        self.label.setStyleSheet("background-color:rgb(0,80, 121)")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_pg_cadastro = QtWidgets.QPushButton(self.pg_home)
        self.btn_pg_cadastro.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pg_cadastro.setFont(font)
        self.btn_pg_cadastro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pg_cadastro.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_pg_cadastro.setObjectName("btn_pg_cadastro")
        self.verticalLayout.addWidget(self.btn_pg_cadastro)
        self.Pages.addWidget(self.pg_home)
        self.pg_import = QtWidgets.QWidget()
        self.pg_import.setObjectName("pg_import")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pg_import)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.pg_import)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.progressBar = QtWidgets.QProgressBar(self.pg_import)
        self.progressBar.setStyleSheet("QProgressBar{    background-color: rgba(0, 0, 0,0.1);\n"
"                        color: rgb(255, 255, 255);\n"
"                        border-style: none;\n"
"                        text-align: center;\n"
"                        border-radius:10px;\n"
"}\n"
"QProgressBar::chunk{ \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(6, 75, 149, 255), stop:1 rgba(72, 130, 157, 255));\n"
"    border-radius:10px;\n"
"}")
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txt_file = QtWidgets.QLineEdit(self.pg_import)
        self.txt_file.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_file.setFont(font)
        self.txt_file.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txt_file.setStyleSheet("color:rgb(255, 255, 255);")
        self.txt_file.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_file.setObjectName("txt_file")
        self.horizontalLayout_4.addWidget(self.txt_file)
        self.btn_open = QtWidgets.QPushButton(self.pg_import)
        self.btn_open.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open.setFont(font)
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_open.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-top-right-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 68, 102);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_4.addWidget(self.btn_open)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.pg_import)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.btn_cadastrar_2 = QtWidgets.QPushButton(self.pg_import)
        self.btn_cadastrar_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_cadastrar_2.setFont(font)
        self.btn_cadastrar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(0, 20, 30);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #fff;\n"
"    color: black;\n"
"}")
        self.btn_cadastrar_2.setObjectName("btn_cadastrar_2")
        self.horizontalLayout_11.addWidget(self.btn_cadastrar_2)
        self.label_7 = QtWidgets.QLabel(self.pg_import)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.Pages.addWidget(self.pg_import)
        self.pg_cadastro = QtWidgets.QWidget()
        self.pg_cadastro.setObjectName("pg_cadastro")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pg_cadastro)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.pg_cadastro)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.label_8 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.txt_nome = QtWidgets.QLineEdit(self.pg_cadastro)
        self.txt_nome.setStyleSheet("color:rgba(211, 239, 251,1);\n"
"border-bottom: 1px solid white;\n"
"border-radius:None;\n"
"background-color:rgba(85,115,155,0.1);\n"
"font-family:Trebuchet MS;\n"
"font-size:21px;")
        self.txt_nome.setObjectName("txt_nome")
        self.horizontalLayout_5.addWidget(self.txt_nome)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(35, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.txt_usuario = QtWidgets.QLineEdit(self.pg_cadastro)
        self.txt_usuario.setStyleSheet("color:rgba(211, 239, 251,1);\n"
"border-bottom: 1px solid white;\n"
"border-radius:None;\n"
"background-color:rgba(85,115,155,0.1);\n"
"font-family:Trebuchet MS;\n"
"font-size:21px;")
        self.txt_usuario.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txt_usuario.setObjectName("txt_usuario")
        self.horizontalLayout_8.addWidget(self.txt_usuario)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.txt_senha = QtWidgets.QLineEdit(self.pg_cadastro)
        self.txt_senha.setStyleSheet("color:rgba(211, 239, 251,1);\n"
"border-bottom: 1px solid white;\n"
"border-radius:None;\n"
"background-color:rgba(85,115,155,0.1);\n"
"font-family:Trebuchet MS;\n"
"font-size:21px;")
        self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senha.setObjectName("txt_senha")
        self.horizontalLayout_9.addWidget(self.txt_senha)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.txt_senha2 = QtWidgets.QLineEdit(self.pg_cadastro)
        self.txt_senha2.setStyleSheet("color:rgba(211, 239, 251,1);\n"
"border-bottom: 1px solid white;\n"
"border-radius:None;\n"
"background-color:rgba(85,115,155,0.1);\n"
"font-family:Trebuchet MS;\n"
"font-size:21px;")
        self.txt_senha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senha2.setObjectName("txt_senha2")
        self.horizontalLayout_10.addWidget(self.txt_senha2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.cb_perfil = QtWidgets.QComboBox(self.pg_cadastro)
        self.cb_perfil.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_perfil.setFont(font)
        self.cb_perfil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_perfil.setStyleSheet("color: white;")
        self.cb_perfil.setEditable(False)
        self.cb_perfil.setPlaceholderText("")
        self.cb_perfil.setObjectName("cb_perfil")
        self.cb_perfil.addItem("")
        self.cb_perfil.addItem("")
        self.horizontalLayout_7.addWidget(self.cb_perfil)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.pg_cadastro)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.btn_cadastrar = QtWidgets.QPushButton(self.pg_cadastro)
        self.btn_cadastrar.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("QPushButton{\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"    background-color:rgb(65, 195, 95);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(76, 229, 109);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.horizontalLayout_6.addWidget(self.btn_cadastrar)
        self.label_12 = QtWidgets.QLabel(self.pg_cadastro)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.label_8.raise_()
        self.label_18.raise_()
        self.Pages.addWidget(self.pg_cadastro)
        self.pg_contato = QtWidgets.QWidget()
        self.pg_contato.setObjectName("pg_contato")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.pg_contato)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.pg_contato)
        self.label_20.setMinimumSize(QtCore.QSize(0, 60))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.label_24 = QtWidgets.QLabel(self.pg_contato)
        self.label_24.setMinimumSize(QtCore.QSize(0, 80))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_14.addWidget(self.label_24)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.pg_contato)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_26 = QtWidgets.QLabel(self.pg_contato)
        self.label_26.setMinimumSize(QtCore.QSize(40, 0))
        self.label_26.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.label_23 = QtWidgets.QLabel(self.pg_contato)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_28 = QtWidgets.QLabel(self.pg_contato)
        self.label_28.setMinimumSize(QtCore.QSize(40, 0))
        self.label_28.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.label_28)
        self.label_21 = QtWidgets.QLabel(self.pg_contato)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_27 = QtWidgets.QLabel(self.pg_contato)
        self.label_27.setMinimumSize(QtCore.QSize(40, 0))
        self.label_27.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27)
        self.label_22 = QtWidgets.QLabel(self.pg_contato)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_13)
        self.label_4 = QtWidgets.QLabel(self.pg_contato)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.Pages.addWidget(self.pg_contato)
        self.pg_sobre = QtWidgets.QWidget()
        self.pg_sobre.setObjectName("pg_sobre")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pg_sobre)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.pg_sobre)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.label_17 = QtWidgets.QLabel(self.pg_sobre)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_12.addWidget(self.label_17)
        self.Pages.addWidget(self.pg_sobre)
        self.verticalLayout_11.addWidget(self.Pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(1)
        self.tb_base.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_home.setText(_translate("MainWindow", "HOME"))
        self.btn_import.setText(_translate("MainWindow", "IMPORTAR"))
        self.btn_tables.setText(_translate("MainWindow", "TABLES"))
        self.btn_sobre.setText(_translate("MainWindow", "SOBRE"))
        self.btn_contato.setText(_translate("MainWindow", "CONTATO"))
        self.tb_base.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tb_base.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>base</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">ESTOQUE</span></p></body></html>"))
        self.tw_estoque.headerItem().setText(0, _translate("MainWindow", "NFe"))
        self.tw_estoque.headerItem().setText(1, _translate("MainWindow", "Série"))
        self.tw_estoque.headerItem().setText(2, _translate("MainWindow", "Data Emissão"))
        self.tw_estoque.headerItem().setText(3, _translate("MainWindow", "Chave"))
        self.tw_estoque.headerItem().setText(4, _translate("MainWindow", "CNPJ Emitente"))
        self.tw_estoque.headerItem().setText(5, _translate("MainWindow", "Nome Emitente"))
        self.tw_estoque.headerItem().setText(6, _translate("MainWindow", "Valor Nfe"))
        self.tw_estoque.headerItem().setText(7, _translate("MainWindow", "Item Nota"))
        self.tw_estoque.headerItem().setText(8, _translate("MainWindow", "UN"))
        self.tw_estoque.headerItem().setText(9, _translate("MainWindow", "Quantidade"))
        self.tw_estoque.headerItem().setText(10, _translate("MainWindow", "Descrição"))
        self.tw_estoque.headerItem().setText(11, _translate("MainWindow", "Unidade Medida"))
        self.tw_estoque.headerItem().setText(12, _translate("MainWindow", "Valor Produto"))
        self.tw_estoque.headerItem().setText(13, _translate("MainWindow", "Data Importação"))
        self.tw_estoque.headerItem().setText(14, _translate("MainWindow", "Usuario"))
        self.tw_estoque.headerItem().setText(15, _translate("MainWindow", "Data Saída"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">SAÍDA</span></p></body></html>"))
        self.tw_saida.headerItem().setText(0, _translate("MainWindow", "NFe"))
        self.tw_saida.headerItem().setText(1, _translate("MainWindow", "SERIE"))
        self.tw_saida.headerItem().setText(2, _translate("MainWindow", "USUÁRIO"))
        self.tw_saida.headerItem().setText(3, _translate("MainWindow", "DATA SAÍDA"))
        self.tw_saida.headerItem().setText(4, _translate("MainWindow", "DATA IMPORTAÇÃO"))
        self.btn_gerar.setText(_translate("MainWindow", "GERAR SAÍDA"))
        self.btn_estorno.setText(_translate("MainWindow", "ESTORNO"))
        self.tb_base.setTabText(self.tb_base.indexOf(self.Base), _translate("MainWindow", "Base"))
        self.label_16.setText(_translate("MainWindow", "Geral"))
        self.btn_chart.setText(_translate("MainWindow", "Gerar Grafico"))
        self.btn_excel.setText(_translate("MainWindow", "Gerar Excel"))
        self.txt_filtro.setPlaceholderText(_translate("MainWindow", "Filtro"))
        self.tb_base.setTabText(self.tb_base.indexOf(self.Geral), _translate("MainWindow", "Geral"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">PYTAX</span></p><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">Sistema de Gerenciamento</span></p><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\"><img src=\"_imgs/logo.png\" ></span></p></body></html>"))
        self.btn_pg_cadastro.setText(_translate("MainWindow", "Cadastrar Usuário"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">IMPORTAR XML</span></p></body></html>"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.txt_file.setPlaceholderText(_translate("MainWindow", "Selecione a pasta com os arquivos XML --->"))
        self.btn_open.setText(_translate("MainWindow", "Upload"))
        self.btn_cadastrar_2.setText(_translate("MainWindow", "Importar"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Tela De Cadastro</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\"_imgs/user.png\"/></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">CADASTRAR USUÁRIO</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Nome:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Usuário:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Senha:</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Confirmar senha:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Perfil:</span></p></body></html>"))
        self.cb_perfil.setCurrentText(_translate("MainWindow", "Usuário"))
        self.cb_perfil.setItemText(0, _translate("MainWindow", "Usuário"))
        self.cb_perfil.setItemText(1, _translate("MainWindow", "Administrador"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Contato</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Desenvolvedor: Henrique Willian Testi</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", " <html><head/><body><p><img src=\"_imgs/phone.png\"/></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">(11) 99929-0280</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", " <html><head/><body><p><img src=\"_imgs/email.png\"/></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; allign: bottom; color:#ffffff;\">testihenrique@gmail.com</span></p><p align=\"center\"><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", " <html><head/><body><p><img src=\"_imgs/instagram.png\"/></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Henry_tst</span></p><p><br/></p><p align=\"center\"><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Sobre</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Este sistema faz a importação de arquivos XML e faz o controle do estoque de acordo com a entrada de notas e saídas apontadas pelo usuário.</span></p></body></html>"))
